name: Build - Linux
description: 'Build Linux release'

inputs:
  runtime:
    description: '.NET runtime'
    required: true
  runtime_deb:
    description: 'Debian runtime'
    required: true
  
runs:
  using: "composite"
  steps:

  - name: Build release
    run: dotnet publish cypnode --configuration Release --self-contained --runtime ${{ inputs.runtime }} --output publish/cypnode/${{ inputs.runtime }}
    shell: bash

  - name: Package tar.gz
    run: |
      pushd publish/cypnode/${{ inputs.runtime }}/

      tar -czf "cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz" *
      sha256sum cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz > cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz.sha256
        
      mv cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz        ${{ github.workspace }}
      mv cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz.sha256 ${{ github.workspace }}

      popd
    shell: bash

  - name: Package deb
    run: |
      cp -r install/linux/debian .

      sed -i 's/\$RUNTIME/${{ inputs.runtime }}/g'                 ./debian/rules
      sed -i "s/\$VERSION/$VERSION/g"                              ./debian/changelog
      sed -i "s/\$TIMESTAMP/$(date +"%a, %d %b %Y %H:%M:%S %z")/g" ./debian/changelog

      dpkg-buildpackage -b --no-sign -a ${{ inputs.runtime_deb }}

      sha256sum ../cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime_deb }}.deb > ../cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime_deb }}.deb.sha256

      mv ../*.deb        ${{ github.workspace }}
      mv ../*.deb.sha256 ${{ github.workspace }}
    shell: bash
