name: Build - Linux
description: 'Build Linux release'

inputs:
  runtime:
    description: '.NET runtime'
    required: true
  
runs:
  using: "composite"
  steps:

  - name: Build release
    run: dotnet publish cypnode --configuration Release --self-contained --runtime ${{ inputs.runtime }} --output publish/cypnode/${{ inputs.runtime }}
    shell: bash

  - name: Package tar.gz
    run: |
      pushd publish/cypnode/${{ inputs.runtime }}/

      tar -czf "cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz" *
      sha256sum cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz > cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz.sha256
        
      mv cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz        ${{ github.workspace }}
      mv cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz.sha256 ${{ github.workspace }}

      popd
    shell: bash
