name: build cypher node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101' # SDK Version to use.
        
    - name: Checkout latest
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Lint code base
      uses: github/super-linter@v3
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_BASH: true
        VALIDATE_CSHARP: true
        VALIDATE_DOCKERFILE: true
        # TODO: Enable JSCPD before mainnet. Until then, duplicate code may exist.
        # VALIDATE_JSCPD: true
        VALIDATE_JSON: true
        VALIDATE_MARKDOWN: true
        VALIDATE_POWERSHELL: true
        VALIDATE_SHELL_SHFMT: true
      
    - name: Run unit tests
      run: dotnet test
      
    - name: Build cypher
      run:  |
        dotnet restore cypher.sln
        dotnet publish cypnode --output publish/cypnode --configuration Release
        
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          ${{ github.workspace }}/publish/cypnode/
