name: build cypher node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Run Id and Run Number
      run: echo Run $GITHUB_RUN_ID.$GITHUB_RUN_NUMBER
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.101' # SDK Version to use.
    - name: Checkout latest
      uses: actions/checkout@master
    - name: build cypher
      run:  |
        dotnet restore cypher.sln
        dotnet publish cypnode --output publish/cypnode --configuration Release
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          cypher/publish/cypnode/
    #- uses: actions/setup-ruby@v1
    #- name: Send Webhook Notification
    #  if: always()
    #  env:
    #    JOB_STATUS: ${{ job.status }}
    #    WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    #    HOOK_OS_NAME: ${{ runner.os }}
    #    WORKFLOW_NAME: ${{ github.workflow }}
    #  run: |
    #    git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
    #    bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
    #  shell: bash
