name: build cypher node release

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  validate-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        uses: ./.github/actions/get-version

      - name: Verify AssemblyVersion core
        run: ./.github/actions/get-version/validate.sh ./core/core.csproj ${{ env.VERSION }}
        shell: bash

      - name: Verify AssemblyVersion node
        run: ./.github/actions/get-version/validate.sh ./node/node.csproj ${{ env.VERSION }}
        shell: bash

  build-linux-macos:
    needs: validate-version
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        uses: ./.github/actions/get-version

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Create linux-x64 package
        uses: ./.github/actions/build-tar-gz
        with:
          runtime: 'linux-x64'

      - name: Create linux-arm64 package
        uses: ./.github/actions/build-tar-gz
        with:
          runtime: 'linux-arm64'

      - name: Create osx-x64 package
        uses: ./.github/actions/build-tar-gz
        with:
          runtime: 'osx-x64'

      - name: Create releases
        id: gh-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: cypher-cyphernetworknode_${{ env.VERSION }}*.*
          name: Release v${{ env.VERSION }}

  build-windows:
    needs: validate-version
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        uses: ./.github/actions/get-version

      - name: Create windows installer
        uses: ./.github/actions/build-windows

      - name: Create Windows release
        id: gh-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: cypher-cypnode_${{ env.VERSION }}*.*
