name: build cypher node release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # Use latest SDK version

    - name: Checkout latest
      uses: actions/checkout@v2

    - name: build cypher
      run:  |
        dotnet restore cypher.sln
        dotnet publish cypnode --configuration Release                                        --output publish/cypnode/generic
        dotnet publish cypnode --configuration Release --self-contained --runtime linux-x64   --output publish/cypnode/linux-x64
        dotnet publish cypnode --configuration Release --self-contained --runtime linux-arm   --output publish/cypnode/linux-arm
        dotnet publish cypnode --configuration Release --self-contained --runtime linux-arm64 --output publish/cypnode/linux-arm64
        dotnet publish cypnode --configuration Release --self-contained --runtime osx-x64     --output publish/cypnode/osx-x64
        dotnet publish cypnode --configuration Release --self-contained --runtime win-x64     --output publish/cypnode/windows-x64
        dotnet publish cypnode --configuration Release --self-contained --runtime win-x86     --output publish/cypnode/windows-x86

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Generate release artifact - generic zip
      id: gen_artifact_generic
      run: |
        pushd ${{ github.workspace }}/publish/cypnode/generic
        zip -r ${OUTPUT_FILE} *
        sha256sum ${OUTPUT_FILE} > ${OUTPUT_FILE}.sha256
        mv ${OUTPUT_FILE} ${{ github.workspace }}
        mv ${OUTPUT_FILE}.sha256 ${{ github.workspace }}
        popd
      env:
        OUTPUT_FILE: "cypher-${{ steps.get_version.outputs.VERSION }}.zip"
        
    - name: Generate release artifact - linux-x64 tar.gz
      run: |
        pushd ${{ github.workspace }}/publish/cypnode/linux-x64
        tar -czf ${OUTPUT_FILE} *
        sha256sum ${OUTPUT_FILE} > ${OUTPUT_FILE}.sha256
        mv ${OUTPUT_FILE} ${{ github.workspace }}
        mv ${OUTPUT_FILE}.sha256 ${{ github.workspace }}
        popd
      env:
        OUTPUT_FILE: "cypher-${{ steps.get_version.outputs.VERSION }}-linux-x64.tar.gz"
        
    - name: Generate release artifact - linux-arm tar.gz
      run: |
        pushd ${{ github.workspace }}/publish/cypnode/linux-arm
        tar -czf ${OUTPUT_FILE} *
        sha256sum ${OUTPUT_FILE} > ${OUTPUT_FILE}.sha256
        mv ${OUTPUT_FILE} ${{ github.workspace }}
        mv ${OUTPUT_FILE}.sha256 ${{ github.workspace }}
        popd
      env:
        OUTPUT_FILE: "cypher-${{ steps.get_version.outputs.VERSION }}-linux-arm.tar.gz"
        
    - name: Generate release artifact - linux-arm64 tar.gz
      run: |
        pushd ${{ github.workspace }}/publish/cypnode/linux-arm64
        tar -czf ${OUTPUT_FILE} *
        sha256sum ${OUTPUT_FILE} > ${OUTPUT_FILE}.sha256
        mv ${OUTPUT_FILE} ${{ github.workspace }}
        mv ${OUTPUT_FILE}.sha256 ${{ github.workspace }}
        popd
      env:
        OUTPUT_FILE: "cypher-${{ steps.get_version.outputs.VERSION }}-linux-arm64.tar.gz"

    - name: Generate release artifact - osx-x64 tar.gz
      run: |
        pushd ${{ github.workspace }}/publish/cypnode/osx-x64
        tar -czf ${OUTPUT_FILE} *
        sha256sum ${OUTPUT_FILE} > ${OUTPUT_FILE}.sha256
        mv ${OUTPUT_FILE} ${{ github.workspace }}
        mv ${OUTPUT_FILE}.sha256 ${{ github.workspace }}
        popd
      env:
        OUTPUT_FILE: "cypher-${{ steps.get_version.outputs.VERSION }}-osx-x64.tar.gz"
        
    - name: Generate release artifact - windows-x64 zip
      run: |
        pushd ${{ github.workspace }}/publish/cypnode/windows-x64
        zip -r ${OUTPUT_FILE} *
        sha256sum ${OUTPUT_FILE} > ${OUTPUT_FILE}.sha256
        mv ${OUTPUT_FILE} ${{ github.workspace }}
        mv ${OUTPUT_FILE}.sha256 ${{ github.workspace }}
        popd
      env:
        OUTPUT_FILE: "cypher-${{ steps.get_version.outputs.VERSION }}-windows-x64.zip"

    - name: Generate release artifact - windows-x86 zip
      run: |
        pushd ${{ github.workspace }}/publish/cypnode/windows-x86
        zip -r ${OUTPUT_FILE} *
        sha256sum ${OUTPUT_FILE} > ${OUTPUT_FILE}.sha256
        mv ${OUTPUT_FILE} ${{ github.workspace }}
        mv ${OUTPUT_FILE}.sha256 ${{ github.workspace }}
        popd
      env:
        OUTPUT_FILE: "cypher-${{ steps.get_version.outputs.VERSION }}-windows-x86.zip"

    - name: Create release
      id: gh-release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: cypher-${{ steps.get_version.outputs.VERSION }}*.*
