name: build cypher node release

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        uses: ./.github/actions/get-version

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Prepare Linux build environment
        uses: ./.github/actions/build-env-prepare-linux

      - name: Create linux-x64 package
        uses: ./.github/actions/build-linux
        with:
          runtime: 'linux-x64'
          runtime_deb: 'amd64'

      - name: Create linux-arm package
        uses: ./.github/actions/build-linux
        with:
          runtime: 'linux-arm'
          runtime_deb: 'armhf'

      - name: Create linux-arm64 package
        uses: ./.github/actions/build-linux
        with:
          runtime: 'linux-arm64'
          runtime_deb: 'arm64'

      - name: Create releases
        id: gh-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: cypher-cypnode_${{ env.VERSION }}*.*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        uses: ./.github/actions/get-version

      - name: Create Windows release
        id: gh-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: cypher-cypnode_$VERSION*.msi
